# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testwidage' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testwidage
  
  pod 'Masonry'
  pod 'Mantle'
  pod 'Realm'
end

target 'widage' do
  pod 'Masonry'
  pod 'Mantle'
  pod 'Realm'
end
